version: '3.4'

services:
  projectservices:
    image: ${DOCKER_REGISTRY-}projectservices
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=192.168.100.116\\SQLEXPRESS;Database=projectservices;User=sa;Password=sa;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5005:5005"
      - "5006:5006"
    restart: on-failure
    container_name: projectservices
    
